#!/bin/bash
# =============================================================================
# NetSendo - Quick Installation Script
# =============================================================================
# Downloads and starts NetSendo using pre-built Docker images.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/NetSendo/NetSendo/main/install.sh | bash
#
# Options:
#   VERSION=1.0.0 ./install.sh    # Install specific version
#   VERSION=latest ./install.sh   # Install latest (default)
# =============================================================================

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
NETSENDO_VERSION="${VERSION:-latest}"
INSTALL_DIR="${INSTALL_DIR:-./netsendo}"
GITHUB_REPO="NetSendo/NetSendo"

echo -e "${BLUE}"
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                                                               ║"
echo "║              NetSendo Installation Script                     ║"
echo "║                                                               ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

echo -e "${YELLOW}📦 Installing NetSendo version: ${NETSENDO_VERSION}${NC}"
echo ""

# Check for Docker
if ! command -v docker &> /dev/null; then
    echo -e "${RED}❌ Docker is not installed. Please install Docker first.${NC}"
    echo "   Visit: https://docs.docker.com/get-docker/"
    exit 1
fi

# Check for Docker Compose
if ! docker compose version &> /dev/null; then
    echo -e "${RED}❌ Docker Compose is not available. Please update Docker.${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Docker and Docker Compose found${NC}"

# Create directory
if [ -d "$INSTALL_DIR" ]; then
    echo -e "${YELLOW}⚠️  Directory $INSTALL_DIR already exists${NC}"
    read -p "   Overwrite? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

echo -e "${BLUE}📥 Downloading configuration files...${NC}"

# Download docker-compose.prod.yml
curl -fsSL "https://raw.githubusercontent.com/${GITHUB_REPO}/main/docker-compose.prod.yml" -o docker-compose.yml

# Download nginx config
mkdir -p docker/nginx
curl -fsSL "https://raw.githubusercontent.com/${GITHUB_REPO}/main/docker/nginx/default.conf" -o docker/nginx/default.conf

# Create .env file
cat > .env << EOF
# NetSendo Configuration
# Generated by installation script

# Application
APP_NAME=NetSendo
APP_ENV=production
APP_DEBUG=false
APP_URL=http://localhost:8080
APP_LOCALE=en

# Version
NETSENDO_VERSION=${NETSENDO_VERSION}

# Database
DB_CONNECTION=mysql
DB_HOST=db
DB_PORT=3306
DB_DATABASE=netsendo
DB_USERNAME=netsendo
DB_PASSWORD=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 24)

# Redis
REDIS_HOST=redis
REDIS_PORT=6379

# Mail
MAIL_HOST=mailpit
MAIL_PORT=1025
MAIL_FROM_ADDRESS=noreply@netsendo.local
MAIL_FROM_NAME=NetSendo

# Ports
HTTP_PORT=8080
DB_PORT=33006
MAILPIT_HTTP_PORT=8025
MAILPIT_SMTP_PORT=1025
EOF

echo -e "${GREEN}✅ Configuration files created${NC}"

echo -e "${BLUE}🚀 Starting NetSendo...${NC}"

# Pull and start
docker compose pull
docker compose up -d

echo ""
echo -e "${GREEN}╔═══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║                                                               ║${NC}"
echo -e "${GREEN}║              ✅ NetSendo installed successfully!              ║${NC}"
echo -e "${GREEN}║                                                               ║${NC}"
echo -e "${GREEN}╚═══════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${BLUE}📍 Access your application:${NC}"
echo "   • Web App:  http://localhost:8080"
echo "   • Mailpit:  http://localhost:8025"
echo ""
echo -e "${BLUE}📋 Useful commands:${NC}"
echo "   • View logs:  docker compose logs -f"
echo "   • Stop:       docker compose down"
echo "   • Start:      docker compose up -d"
echo ""
echo -e "${YELLOW}🔄 To update to a new version:${NC}"
echo "   1. Edit .env and change NETSENDO_VERSION"
echo "   2. Run: docker compose pull && docker compose up -d"
echo ""
